### ISSUE TITLE
Not able to set password using forgot password

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#185]
Hi Guys,

I used the forgot password link in newadminsuite (Sumeetika) to set a new password but it always says that the link has expired. I am using the link to set the password without any delay.

![link_expires](https://user-images.githubusercontent.com/26539946/27426890-b55d58fe-575a-11e7-9bd8-fbcc300b0367.png)

however, the password appears to be set as I am able to log in fine. 

The message is confusing and should not come if the password was changed successfully.

**Comment by hitesh-opg** [comment]
Hi guys, was checking again and now the password that I set using the link is not working

so it appears the password reset is completely not working

**Comment by deepika-Gopala** [comment]
Hi hitesh,

Reset password is working fine. Have tried it with two accounts.

The scenario here is : one the link is used to change the password , user  cannot used the same link again , that is why user will be getting expired error.
in that case user has to try the forgot password again and click on the new link in the mail.

**Comment by hitesh-opg** [comment]
Hi Deepika,

I am not using old link to set the password, see attached

[2017-06-22-1552-30.zip](https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/files/1094438/2017-06-22-1552-30.zip)

If it is specific to me then also it will be good to know why as I can be of the client using it, will be good to know what I am doing wrong

**Comment by pavithra-opg** [comment]
Hi Deepika,

I tried to reset the password by clicking on Forgot password,set a new password using the link(got a success message) so tried to login with the new password I set it says "Username or Password invalid". 
I logged in as administrator,changed my account password and then tried to login using the set password, it allowed me in.

**Comment by hitesh-opg** [comment]
Hi Deepika,

On adding to Pavi's note on forgot password, I am still facing the issue that says link expired.

I have deleted my browser history many times but no result. I guess, this is a one off scenario happening to me but will be good to have some thoughts on what could be the reason.

If the same happens with any client, we should be able to offer some help to get out of this. I am not sure what to do.

If you want I can show you this in my system

**Comment by deepika-Gopala** [comment]
HI hitesh,


This is something to be handled by api team , cause the message that we are showing is comming from the api , so its been assigned to abhi .

@abhi-onepoint  please check this out.

Thanks,

**Comment by deepika-Gopala** [comment]
We will have a look into pavithras issue.

**Comment by akshatha-opg** [comment]
Hi,
We have resolved forgot password issue.
Problem is with multiple account on a single email id. 
And same email has been used to reset password, in this case It gets multiple account while resetting and sets it to some other account.
Fixes made: Suspend other accounts and use one to reset it, it works.
Fixed in web API and released to development.

**Comment by abhi-onepoint** [comment]
-We should not be using email for password reset, if email has been used in multiple account creation.
In such cases system gets confusion to reset account where it has multiple account on a email. and it may do nothing or resets password to other unused account of submitted email .

-If email should be used for reset, then need to ensure a account on a email by suspending other account if exist

-Or user name can be used to reset which is unique (But there is a chance of forgetting that too) and which ensures resetting the password to submitted username.

**Comment by hitesh-opg** [comment]
Thanks,

But at times we want to have multiple account with same e-mail but different usernames.

say, one account for general testing and one for demos to the client.

We do not face any issue with old sms platform, we have been using multiple accounts there. That approach has worked,

Also, in my case I only have one active account, rest all were suspended but it gives link expire error.

**Comment by abhi-onepoint** [comment]
The our new platform logic, development platform is different than sms system.
And please wait for staging release and check after by getting new reset link (We resolved list confusion while resetting, which works on suspending other account- Only update in developement).

**Comment by hitesh-opg** [comment]
I still get this issue, when I try to reset password using account toolkit account in staging.

If it is to do with multiple accounts being created using the same e-mail id, other members (pavi, prabeena) are not facing this.

As it is for my accounts only, I will not say it is critical but when there is time it will be good to check what could be causing this.

**Comment by deepika-Gopala** [comment]
Scenario Found: When a user has more then one accounts for the same email id , sample management import doesnt work , Its always returns sample does not exist. 

This is similar to the reset where new password wont work if there are multiple accounts for the same ID.  Email ID has to be made unique to prevent multiple account creation for same ID.
